version: '3.9'

services:
  postgres:
    image: postgres:15
    env_file: .env.dev
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]

  # redis:
  #   image: redis:7
  #   ports: ["6379:6379"]

  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile.dev
    ports: ["8001:8001"]
    volumes:
      - .:/app
    environment:
      APP_ENV: development
      ENV_PATH: /app/.env.dev
    depends_on: [postgres]

  # web-ui:
  #   build:
  #     context: ./apps/web-ui
  #     dockerfile: Dockerfile.dev
  #   ports: ["3000:3000"]
  #   volumes:
  #     - ./apps/web-ui:/app
  #   env_file: .env.dev
  #   depends_on: [auth-service]

  # api-gateway:
  #   build:
  #     context: ./apps/api-gateway
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - ./apps/api-gateway:/app
  #     - /app/node_modules
  #   env_file: .env.dev
  #   depends_on:
  #     - auth-service
  #     - redis
  #     - postgres

volumes:
  pgdata:
