version: '3.9'

services:
  postgres:
    image: postgres:15
    env_file: .env.dev
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile.dev
    ports: ["8001:8001"]
    volumes:
      - ./services/auth-service:/app
    env_file: .env.dev
    depends_on: [postgres]

  web-ui:
    build:
      context: ./apps/web-ui
      dockerfile: Dockerfile.dev
    ports: ["3000:3000"]
    volumes:
      - ./apps/web-ui:/app
    env_file: .env.dev
    depends_on: [auth-service]

volumes:
  pgdata:
