FROM golang:1.23.4

WORKDIR /app

# Install Air
RUN go install github.com/air-verse/air@latest

# Copy entire repo context (to access go.work + libs + .env.dev)
COPY . .

WORKDIR /app/services/auth-service

# Download deps
RUN go mod tidy

# Run Air with build cmd that specifies the binary location
CMD ["air", "-build.cmd", "go build -o /tmp/auth-service-main", "-build.bin", "/tmp/auth-service-main", "-build.log", "/tmp/auth-service-errors.log"]