FROM node:22.14.0

WORKDIR /app

COPY package*.json ./

# Install nodemon globally for dev
RUN npm install && npm install -g nodemon

COPY . .

EXPOSE 3001

CMD ["nodemon", "--legacy-watch", "src/index.ts"]